Dummy instruction fixes
openhwgroup/cv32e40s pull request #101
Opened 2022-01-18 15:40 UTC by silabs-halfdan

Addressed issues pointed out in #92  :
 - Updated dummy instruction assertions to not have special case around writes.
 - Updated dummy instruction insertion counter to reset when insertion frequency controls are updated.
 - Made dummy instruction part of register file support REGFILE_NUM_WRITE_PORTS

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2022-01-19 09:55 UTC, silabs-oysteink requested changes
If we need to reset on lockup that would require a change, otherwise I think it looks good.

2022-01-19 09:55 UTC, silabs-oysteink commented on rtl/cv32e40s_cs_registers.sv
> +      assign xsecure_ctrl_o.cntrst = cpuctrl_we || secureseed0_we;
Would we also need to reset the counter when a LFSR reset has been done due to lockup?

2022-01-19 10:23 UTC, silabs-halfdan commented on rtl/cv32e40s_cs_registers.sv
> +      assign xsecure_ctrl_o.cntrst = cpuctrl_we || secureseed0_we;
It is not strictly necessary as the count compare value at lockup is 0, so we will still guarantee the insertion frequency range (and the minimum one cycle between) for any new value.
But I agree it would look cleaner to include it, I can push an update.

2022-01-19 10:59 UTC, silabs-oysteink approved these changes

2022-01-20 10:30 UTC, Silabs-ArjanB requested changes

2022-01-20 10:30 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +      assign xsecure_ctrl_o.cntrst = cpuctrl_we || secureseed0_we || lfsr_lockup[0];
If secureseed0 is written by software (which happens in WB), then this becomes visible in the IF stage. The instructions in ID and EX should have seen this update as well (and in the current code they don't).

Please add a branch to 'pc plus 4' in case of software CSR writes to all three secureseed CSRs (similar code to the one related to cpuctrl_wr_in_wb_i in the controller FSM).

2022-01-20 11:38 UTC, silabs-halfdan commented on rtl/cv32e40s_cs_registers.sv
> +      assign xsecure_ctrl_o.cntrst = cpuctrl_we || secureseed0_we || lfsr_lockup[0];
Good point, I'll push an update.

2022-01-20 14:01 UTC, Silabs-ArjanB approved these changes

2022-01-20 16:24 UTC, silabs-oysteink approved these changes

2022-01-20 16:28 UTC, Silabs-ArjanB requested changes

2022-01-20 16:28 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +  assign secureseed_wr_in_wb_o = secureseed0_we || secureseed0_we || secureseed0_we;
Copy/paste error here; all same write enable

2022-01-21 08:10 UTC, silabs-halfdan commented on rtl/cv32e40s_cs_registers.sv
> +  assign secureseed_wr_in_wb_o = secureseed0_we || secureseed0_we || secureseed0_we;
Well spotted, updating now.

2022-01-21 09:41 UTC, Silabs-ArjanB approved these changes

2022-01-21 09:42 UTC, merged