Instantiated shadow flops for csr hardening
openhwgroup/cv32e40s pull request #106
Opened 2022-01-24 15:49 UTC by silabs-halfdan

Instantiated shadow flops for csr hardening to avoid it being optimized away.

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2022-01-24 17:11 UTC, Silabs-ArjanB requested changes

2022-01-24 17:11 UTC, Silabs-ArjanB commented on bhv/cv32e40s_sim_sffs.sv
> +   input  logic  set_n,
Just keep using rst_n instead of set_n (although it indeed sets a flop)

2022-01-24 17:11 UTC, Silabs-ArjanB commented on docs/user_manual/source/getting_started.rst
> +* ``set_n`` : Set (i.e., reset value == 1)
* ``rst_n`` : Reset (with reset value == 1)

2022-01-24 17:11 UTC, Silabs-ArjanB commented on docs/user_manual/source/getting_started.rst
> +* ``rst_n`` : Reset
* ``rst_n`` : Reset (with reset value == 0)

2022-01-24 17:11 UTC, Silabs-ArjanB commented on rtl/cv32e40s_csr.sv
> +          assign shadow_q[i] = 1'b0;
This doesn't seem to match the original implementation.

2022-01-24 17:11 UTC, Silabs-ArjanB commented on rtl/cv32e40s_csr.sv
> +  generate
Why would above rdata_q not get optimized away now? Maybe put both shadow and non-shadow register inside generate (and original RTL code in else branch).

Did you analyze the clock gating behavior for these CSRs; are we getting clock gates in the netlist for wide CSRs if they are not being written?

2022-01-25 08:16 UTC, silabs-halfdan commented on bhv/cv32e40s_sim_sffs.sv
> +   input  logic  set_n,
Will update to use rst_n

2022-01-25 08:36 UTC, silabs-halfdan commented on rtl/cv32e40s_csr.sv
> +  generate
Good point, will add for rdata_q too to ensure both are kept.

We are getting a clock gate (with wr_en_i as enable) in the netlist with this data gating syntax.

2022-01-25 08:36 UTC, silabs-halfdan commented on rtl/cv32e40s_csr.sv
> +          assign shadow_q[i] = 1'b0;
Not sure what happened here... Will implement correctly.

2022-01-25 08:54 UTC, Silabs-ArjanB commented on rtl/cv32e40s_csr.sv
> +  generate
Is the clock gate getting shared between the base flops and the shadow flops?

2022-01-25 08:54 UTC, Silabs-ArjanB commented on rtl/cv32e40s_csr.sv
> +          assign shadow_q[i] = 1'b0;
Please run SEC as well.

2022-01-25 12:17 UTC, silabs-halfdan commented on rtl/cv32e40s_csr.sv
> +          assign shadow_q[i] = 1'b0;
Will do

2022-01-25 12:17 UTC, silabs-halfdan commented on rtl/cv32e40s_csr.sv
> +  generate
Not always it seems. I will instantiate the clock gate.

2022-01-26 14:22 UTC, silabs-halfdan commented
This PR is now SEC clean.

2022-01-27 10:01 UTC, Silabs-ArjanB requested changes

2022-01-27 10:01 UTC, Silabs-ArjanB commented on rtl/include/cv32e40s_pkg.sv
> +parameter CSR_DCSR_MASK     = 32'b1111_0000_0000_0000_1000_1001_1100_0111; // NMI bit taken from ctrl_fsm
I like that you introduced these masks, but now we have duplication of information. For example the CSR_MEPC_MASK is also used hard coded as follows:

   mepc_n                   = csr_wdata_int & ~32'b1;

We should replace that line by:

   mepc_n                   = csr_wdata_int & CSR_MEPC_MASK;
   
Please use the introduced masks where possible (i.e. not always, as not all _n values depend on csr_wdata_int only (e.g. I would expect the dcsr_n assignment to remain as it is))

2022-01-27 10:28 UTC, silabs-halfdan commented on rtl/cv32e40s_csr.sv
> +         .clk_o        ( cg_clk       ));
Will update the naming.

2022-01-27 15:34 UTC, silabs-halfdan commented on rtl/include/cv32e40s_pkg.sv
> +parameter CSR_DCSR_MASK     = 32'b1111_0000_0000_0000_1000_1001_1100_0111; // NMI bit taken from ctrl_fsm
This is now added, we might want to re-visit the masking to make it consistent (e.g. mepc_n is not always masked).

2022-01-27 15:40 UTC, Silabs-ArjanB approved these changes

2022-01-27 15:40 UTC, merged