Precursor to PC hardening, multi cycle jumps and branches
openhwgroup/cv32e40s pull request #112
Opened 2022-02-04 08:23 UTC by silabs-oysteink

Jumps (including mret) and branches are now treated as multi cycle / multi operation instructions.

These instructions will now spend two cycles in ID, EX and WB.
A 'last_op' bit has been added to the id_ex_pipe and ex_wb_pipe, this bit will be low for the
first cycle of jumps and branhces, and high for the second cycle and any other instructions.
wb_valid will only go high for instructions with last_op=1.

- Passes ci_check.

- Not SEC clean.
-- Non-taken branches gets one cycle extra penalty
-- Jumps will get different stall conditions making it non-SEC

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2022-02-04 11:06 UTC, Silabs-ArjanB requested changes

2022-02-04 11:06 UTC, Silabs-ArjanB commented on sva/cv32e40s_id_stage_sva.sv
> +  a_mret_self_stall :
Same remark as above. I think last is used for the wrong pipeline stages.

2022-02-04 11:24 UTC, silabs-oysteink commented on rtl/cv32e40s_controller_bypass.sv
> +                              (id_ex_pipe_i.instr_valid && (id_ex_pipe_i.csr_en || (id_ex_pipe_i.sys_en && id_ex_pipe_i.sys_mret_insn && id_ex_pipe_i.last_op))) ||
Agreed, fix implemented.

2022-02-04 11:27 UTC, silabs-oysteink commented on rtl/cv32e40s_ex_stage.sv
> +    end else begin //!SECURE
Done

2022-02-04 11:27 UTC, silabs-oysteink commented on rtl/cv32e40s_id_stage.sv
> +  logic                 last;
Done

2022-02-04 11:28 UTC, silabs-oysteink commented on rtl/cv32e40s_id_stage.sv
> +      assign jmp_bch_insn = ((alu_jmp || alu_jmpr || alu_bch) && alu_en) || (sys_mret_insn && sys_en);
Done

2022-02-04 12:19 UTC, silabs-oysteink commented on sva/cv32e40s_controller_fsm_sva.sv
> +                        ((id_ex_pipe_i.csr_en || (id_ex_pipe_i.sys_en && id_ex_pipe_i.sys_mret_insn && id_ex_pipe_i.last_op)) && id_ex_pipe_i.instr_valid) ||
Done

2022-02-04 12:24 UTC, silabs-oysteink commented on sva/cv32e40s_id_stage_sva.sv
> +  a_mret_self_stall :
Done

2022-02-04 12:54 UTC, silabs-oysteink commented on rtl/cv32e40s_controller_fsm.sv
> +  logic jump_taken_n;
Yes, I think the best option is to manually introduce these changes in the 40X after we get this PR merged, to avoid too much back-and-forth and multiple PRs/merges.

2022-02-09 06:55 UTC, silabs-oysteink commented on rtl/cv32e40s_id_stage.sv
> +  assign multi_op_id_stall = !last_op && (if_id_pipe_i.instr_valid); //todo:ok Zce push/pop will use this
As far as I see it, it doesn't matter if we use the registered instr_valid or the local instr_valid, as the logic for id_ready_o and id_valid_o already factors in halt_id and kill_id.

2022-02-09 08:39 UTC, Silabs-ArjanB requested changes

2022-02-09 08:39 UTC, Silabs-ArjanB commented on rtl/cv32e40s_controller_fsm.sv
> +    if ((id_valid_i && ex_ready_i && id_ex_pipe_i.last_op && branch_taken_q) || ctrl_fsm_o.kill_ex) begin
The code is clear and consistent now, but I still doubt whether it is correct. We really want to clear the flag when the target instruction enters EX, not when the last part of the target instruction enters EX I believe. I think you just need to add some helper logic to know whether the original branch has left EX.

2022-02-09 08:39 UTC, Silabs-ArjanB commented on rtl/cv32e40s_id_stage.sv
> +  assign multi_op_id_stall = !last_op && (if_id_pipe_i.instr_valid); //todo:ok Zce push/pop will use this
Can you please explain the reasoning in the code otherwise this question will just keep coming up.

2022-02-09 09:55 UTC, Silabs-ArjanB commented on rtl/cv32e40s_controller_fsm.sv
> +    if ((id_valid_i && ex_ready_i && id_ex_pipe_i.last_op && branch_taken_q) || ctrl_fsm_o.kill_ex) begin
Misread above code (I mistakenly thought the last_op was for the instruction in ID). Agreed now.

2022-02-09 09:56 UTC, Silabs-ArjanB approved these changes

2022-02-09 09:57 UTC, merged