Add PMP
openhwgroup/cv32e40s pull request #22
Opened 2021-07-06 11:02 UTC by silabs-oivind

Add PMP and related CSR's.
PMP is instantiated in MPU, meaning it's on both data- and instruction side.
Controller handles PMP errors on instruction side, but not yet on data side.
Not SEC clean, because access to PMP CSR registers no longer result in an exception.

2021-07-06 12:09 UTC, Silabs-ArjanB requested changes

2021-07-06 12:09 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +        CSR_PMPMSECCFG0: begin
How about CSR_PMPMSECCFG1?

2021-07-06 12:09 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +
How about CSR_PMPMSECCFG1?

2021-07-06 12:09 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +  output pmp_cfg_t        csr_pmp_cfg_o [PMP_MAX_REGIONS],
Can you add an CSR output struct instead and feed that into IF and LSU instead (the PMP boundary can remain unchanged)? Eventually we want to put all CSR module outputs in that struct (but that can be done in a later commit)

2021-07-06 12:09 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +  parameter PMP_NUM_REGIONS  = 0,
In case you used Ibex code in this module (I don't know), please add their copyright header as well.

2021-07-07 07:40 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +        CSR_PMPMSECCFG0: begin
There are currently no implemented bits in CSR_PMPMSECCFG1, but it is part of the specification. It was only added in the decoder to avoid getting an exception when accessing it.

2021-07-07 07:40 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +
Same as above

2021-07-07 07:43 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +  output pmp_cfg_t        csr_pmp_cfg_o [PMP_MAX_REGIONS],
Done. This was not done because the width was initially PMP_NUM_REGIONS, and a top-level RTL parameter can't be used inside the package. After changing the width to PMP_MAX_REGIONS, this works fine.

2021-07-07 07:46 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +  parameter PMP_NUM_REGIONS  = 0,
Added.

2021-07-07 09:37 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +
If it exists in the spec, then it should be made explicit in both the CSR read and CSR write logic

2021-07-07 10:40 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +
Added CSR_PMPMSECCFG1 in CSR access logic.

2021-07-07 10:53 UTC, Silabs-ArjanB approved these changes

2021-07-07 10:53 UTC, merged