Implement integrity attribution in PMA and MPU
openhwgroup/cv32e40s pull request #299
Opened 2022-09-08 13:12 UTC by silabs-oivind

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

2022-09-13 10:25 UTC, silabs-oysteink approved these changes

2022-09-14 07:46 UTC, Silabs-ArjanB requested changes

2022-09-14 07:46 UTC, Silabs-ArjanB commented on rtl/cv32e40s_mpu.sv
> +      parameter int          OUTSTND_CNT_WIDTH            = 2,
int unsigned

2022-09-14 07:46 UTC, Silabs-ArjanB commented on rtl/cv32e40s_mpu.sv
> +  assign core_resp_o.integrity  = integrity_fifo_q[core_outstnd_cnt_q];
(Without having looked at the assertions yet) Can you add an assertion that core_outstnd_cnt_q > 0 whenever core_resp_valid_o == 1? (This is difficult to see because the timing of mpu_err_trans_valid is not obvious)

2022-09-15 07:14 UTC, closed without merging