Implement PMA integrity
openhwgroup/cv32e40s pull request #303
Opened 2022-09-15 07:18 UTC by silabs-oivind

Send PMA integrity bit to the bus interface modules
SEC clean

2022-09-15 08:08 UTC, silabs-oysteink approved these changes

2022-09-16 06:47 UTC, Silabs-ArjanB requested changes

2022-09-16 06:47 UTC, Silabs-ArjanB commented on rtl/cv32e40s_mpu.sv
> +    .pma_integrity_o            ( pma_integrity        ),
pma_integrity -> bus_trans_integrity (consistent naming)

2022-09-16 06:47 UTC, Silabs-ArjanB commented on rtl/include/cv32e40s_pkg.sv
> +  logic                        integrity;
Add comment that this bit will not be actually passed onto OBI

2022-09-16 06:47 UTC, Silabs-ArjanB commented on rtl/include/cv32e40s_pkg.sv
> +  logic                           integrity;
Add comment that this bit will not be actually passed onto OBI

2022-09-16 07:13 UTC, silabs-oivind commented on rtl/cv32e40s_mpu.sv
> +    .pma_integrity_o            ( pma_integrity        ),
Updated.

2022-09-16 07:13 UTC, silabs-oivind commented on rtl/include/cv32e40s_pkg.sv
> +  logic                        integrity;
Done.

2022-09-16 07:13 UTC, silabs-oivind commented on rtl/include/cv32e40s_pkg.sv
> +  logic                           integrity;
Done.

2022-09-16 08:32 UTC, Silabs-ArjanB approved these changes

2022-09-16 08:32 UTC, merged