Added LSU integrity checking.
openhwgroup/cv32e40s pull request #305
Opened 2022-09-23 12:26 UTC by silabs-oysteink

LSU will signal intergrity_err_o (fans into alert_major_o) immediately when any parity error on data_gnt_i or data_rvalid_i is detected. Similarly for errors on data_rchk_i, an integrity_err_o will be flagged if cpuctrl.integrity is set and the transaction is from a PMA region with integrity enabled.

Any load or store with integrity errors as described above will generate an NMI.

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

2022-09-26 07:28 UTC, silabs-oivind commented on rtl/cv32e40s_rchk_check.sv
> +//                 and signal an error if enabled and checksums does not match//
Add explanation on why enable is 2 bits.

2022-09-26 07:48 UTC, silabs-oivind commented on sva/cv32e40s_controller_fsm_sva.sv
> -  input logic [1:0]     lsu_err_wb_i,
Update assertion in this file to account for added bits in lsu_err-wb (even though the assertion is commented out for some reason)

2022-09-26 07:51 UTC, silabs-oivind commented on rtl/cv32e40s_lsu_response_filter.sv
> +   output logic [2:0]     err_o  // bit0: flag for bus error, bit1: flag for integrity error, bit2: type (1 for store, 0 for load)
Consider using a struct for err_o. For readability.

2022-09-26 07:53 UTC, silabs-oivind commented on rtl/cv32e40s_instr_obi_interface.sv
> +  // Both bits are the same, we always read and always check the fulle rchk
Typo: fulle -> full

2022-09-26 07:57 UTC, silabs-oivind commented on rtl/cv32e40s_data_obi_interface.sv
> +  logic [1:0]     cnt_q;                        // Transaction counter
Calculate cnt_q width based on MAX_OUTSTANDING. Also do the same in cv32e40s_instr_obi_interface.

2022-09-26 09:04 UTC, Silabs-ArjanB requested changes

2022-09-26 09:04 UTC, Silabs-ArjanB commented on rtl/include/cv32e40s_pkg.sv
> +  logic                       rchk_err;
Add comments for these 3 signals that they are not actually passed onto OBI (same remark for obi_inst_resp_t)

2022-09-26 09:51 UTC, silabs-oysteink commented on rtl/cv32e40s_data_obi_interface.sv
> +  /////////////////////////////////////////////////////////////
You're right, the bus-side counter in the LSU response filter is identical (checked the two counters with a temporary assertion). I will remove the counter in the data_obi interface and use the one from the response filter.

2022-09-26 11:11 UTC, silabs-oysteink commented on rtl/cv32e40s_rchk_check.sv
> +//                 and signal an error if enabled and checksums does not match//
Updated description.

2022-09-26 11:12 UTC, silabs-oysteink commented on sva/cv32e40s_controller_fsm_sva.sv
> -  input logic [1:0]     lsu_err_wb_i,
Updated assertion. Still commented, need to adapt it to errors which originates from the write buffer (may come at any time, even when there is no LSU instruction in WB).

2022-09-26 11:12 UTC, silabs-oysteink commented on rtl/cv32e40s_lsu_response_filter.sv
> +   output logic [2:0]     err_o  // bit0: flag for bus error, bit1: flag for integrity error, bit2: type (1 for store, 0 for load)
Added struct.

2022-09-26 11:12 UTC, silabs-oysteink commented on rtl/cv32e40s_instr_obi_interface.sv
> +  // Both bits are the same, we always read and always check the fulle rchk
Fixed

2022-09-26 11:12 UTC, silabs-oysteink commented on rtl/cv32e40s_data_obi_interface.sv
> +  logic [1:0]     cnt_q;                        // Transaction counter
Done

2022-09-26 11:12 UTC, silabs-oysteink commented on rtl/cv32e40s_core.sv
> +    .integrity_err_o       ( integrity_err_lsu  ),
Fixed

2022-09-26 11:13 UTC, silabs-oysteink commented on rtl/cv32e40s_instr_obi_interface.sv
> +  assign rchk_en[0] = m_c_obi_instr_if.s_rvalid.rvalid && xsecure_ctrl_i.cpuctrl.integrity;
Added comment

2022-09-26 11:13 UTC, silabs-oysteink commented on rtl/cv32e40s_alignment_buffer.sv
> +  logic [1:0]  rchk_enable;             // "Global" rchk enable from cpuctrl
Added comment

2022-09-26 11:14 UTC, silabs-oysteink commented on rtl/include/cv32e40s_pkg.sv
> +  logic                       rchk_err;
Comments added

2022-09-26 11:53 UTC, Silabs-ArjanB requested changes

2022-09-26 13:09 UTC, silabs-oysteink commented on rtl/cv32e40s_core.sv
> +  assign m_c_obi_instr_if.resp_payload.rchk_err   = 1'b0; // Tie off here, will we populated in instr_obi_insterface.
Fixed

2022-09-26 13:09 UTC, silabs-oysteink commented on rtl/cv32e40s_core.sv
> +  assign m_c_obi_data_if.resp_payload.parity_err = 1'b0; // Tie off here, will we populated in data_obi_insterface.
Fixed

2022-09-28 08:30 UTC, silabs-oysteink commented
Merging as agreed offline.

2022-09-28 08:30 UTC, merged