Implemented random hint instructions
openhwgroup/cv32e40s pull request #323
Opened 2022-10-11 11:09 UTC by silabs-oysteink

2022-10-11 12:38 UTC, Silabs-ArjanB requested changes

2022-10-11 12:38 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +      // A pipeline flush will also be performed.
Add comment why lfsr_lockup cannot be used here

2022-10-11 12:38 UTC, Silabs-ArjanB commented on rtl/cv32e40s_lfsr.sv
> +  assign lockup_shift = !(|lfsr_n) && shift_i && enable_i;
assign lockup_shift = !(|lfsr_n) && shift_i && !seed_we_i && enable_i;

2022-10-11 12:38 UTC, Silabs-ArjanB commented on rtl/cv32e40s_lfsr.sv
> +  // Detect lockup (all 0's with XOR based feedback) in next cycle due to shift
I think it would be better to prevent lfsr_q updates to a 0 seed altogether by changing the priorities as follows:

1) lockup_o
2) seed_we_i
3) (shift_i)

2022-10-12 06:35 UTC, silabs-oysteink commented on rtl/cv32e40s_cs_registers.sv
> +      // A pipeline flush will also be performed.
Added comment.

2022-10-12 06:36 UTC, silabs-oysteink commented on rtl/cv32e40s_lfsr.sv
> +  assign lockup_shift = !(|lfsr_n) && shift_i && enable_i;
Fixed

2022-10-12 06:36 UTC, silabs-oysteink commented on rtl/cv32e40s_lfsr.sv
> +  // Detect lockup (all 0's with XOR based feedback) in next cycle due to shift
Changed to the proposed prority.

2022-10-12 06:51 UTC, Silabs-ArjanB approved these changes

2022-10-12 06:51 UTC, merged