Updates to mret/xinhv handling.
openhwgroup/cv32e40s pull request #331
Opened 2022-10-26 13:20 UTC by silabs-oysteink

Updated handling of mret related to mcause.mpp and mcause.minhv. No inhv assumes for mpp==PRIV_LVL_U. Unique case violation in cs_registers due to clearing of minhv fixed, assertions added to make sure there is no conflicting writes to mcause.

When merged, this PR will be cherry picked to the E40X to apply the changes there. Should fix issue #498 on CV32E40X when done.

2022-10-26 14:05 UTC, Silabs-ArjanB requested changes

2022-10-26 14:05 UTC, Silabs-ArjanB commented on rtl/cv32e40s_controller_fsm.sv
> +            ctrl_fsm_o.csr_cause.minhv  = mcause_i.minhv;
Can we have an assertion checking that various CLIC related signals are inactive when SMCLIC=0?

E.g.FSM is never in POINTER_FETCH state, ctrl_fsm_o.csr_cause.minhv is 1'b0, mcause_i.minhv = 1'b0, *.instr_meta.clic_ptr = 1'b0, etc.

2022-10-27 06:59 UTC, silabs-oysteink commented on rtl/cv32e40s_controller_fsm.sv
> +            ctrl_fsm_o.csr_cause.minhv  = mcause_i.minhv;
Added assertion.

2022-10-27 07:00 UTC, silabs-oysteink commented on rtl/cv32e40s_cs_registers.sv
> +      if (SMCLIC) begin
Order of if's fixed.

2022-10-27 07:56 UTC, Silabs-ArjanB approved these changes

2022-10-27 07:57 UTC, merged