Signal instruction PMP error on RVFI
openhwgroup/cv32e40s pull request #366
Opened 2022-12-20 11:52 UTC by silabs-oivind

This update has been verified formally by asserting that we signal PMP error on rvfi_trap.cause_type if and only if we have a instruction access fault. Since PMA can also give instruction access fault, PMA had to be disabled to get the assertions to pass. Because of this, the assertions used to verify this are not checked in.

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

2022-12-20 15:25 UTC, silabs-oysteink approved these changes

2022-12-21 07:00 UTC, Silabs-ArjanB requested changes

2022-12-21 07:00 UTC, Silabs-ArjanB commented on bhv/cv32e40s_wrapper.sv
> +         .instr_pmp_err_if_i       ( core_i.if_stage_i.mpu_i.pmp_err                                      ),
This PR does not seem to address the question asked in the original github ticket, i.e. why is the timing of this signal considered okay to be used as 'if' stage timing. Comments need to be added explaining this as it is not obvious.

2023-01-04 12:13 UTC, silabs-oivind commented on bhv/cv32e40s_rvfi_instr_obi.sv
> +        obi_instr.pmp_err                            = fifo_q[rptr_q].pmp_err || fifo_q[rptr_q_inc].pmp_err;
It is correct since the PMP errors are captured with the same timing as OBI address phase signals. Added comments explaining this.

2023-01-04 12:17 UTC, silabs-oivind commented on bhv/cv32e40s_wrapper.sv
> +         .instr_pmp_err_if_i       ( core_i.if_stage_i.mpu_i.pmp_err                                      ),
This signal does not have IF stage timing, but it is only used in cv32e40s_rvfi_instr_obi which aligns it to IF timing. There is a comment in cv32e40s_rvfi_instr_obi stating when the signal is valid. ("pmp_err_i is valid when the MPU accepts a transfer").

2023-01-05 06:45 UTC, Silabs-ArjanB approved these changes

2023-01-05 06:46 UTC, merged