Updated csr.yaml.m4 for easier script parsing, fixed duplicate entries
openhwgroup/cv32e40s pull request #424
Opened 2023-03-21 13:45 UTC by silabs-hfegran

Changes: 
Fixed some entries that would be included twice.
Fixed typos
Merged register definitions for easier parsing

Reason for change: Adapt m4 format to be able to generate bitfield data types for c/systemverilog
Changes that are not bugfixes should have no functional impact on current infrastructure

2023-03-22 07:10 UTC, silabs-hfegran commented
I will likely need to make some more small modifications, please do not merge yet.

2023-03-22 07:34 UTC, Silabs-ArjanB requested changes
Changes requested as commented.

This PR should be done on CV32E40X instead though.

2023-03-22 07:34 UTC, Silabs-ArjanB commented on yaml/csr.yaml.m4
> +]]])
This clause is okay, but the next one is wrong. If V_EXT != 0, then the V bit will be hardwired to 1 (so WARL (0x1))

2023-03-22 07:34 UTC, Silabs-ArjanB commented on yaml/csr.yaml.m4
> +]]])
Same here. This clause is okay, but the next one is wrong. If P_EXT != 0, then the P bit will be hardwired to 1 (so WARL (0x1))

2023-03-22 07:34 UTC, Silabs-ArjanB commented on yaml/csr.yaml.m4
> +ifelse(eval(A_EXT == 0), 1, [[[
A_EXT is no longer a single bit, but can be A_NONE, ZALRSC, A. Only if set to 'A' should the misa.A bit be set to 1. check all uses of A_EXT in this file.

2023-03-22 07:34 UTC, Silabs-ArjanB commented on yaml/csr.yaml.m4
> +          Aliaaas for mstatus.MPIE
Aliaaas -> Alias

2023-05-11 07:13 UTC, Silabs-ArjanB commented
@silabs-hfegran What needs to be done with this PR (except for resolving the merge conflicts)? If it is still relevant when can it be merged?

2023-09-01 10:35 UTC, closed without merging