Fix for issue #388
openhwgroup/cv32e40s pull request #425
Opened 2023-03-24 09:15 UTC by silabs-oivind

2023-03-24 11:54 UTC, silabs-oysteink requested changes

2023-03-24 11:54 UTC, silabs-oysteink commented on rtl/cv32e40s_cs_registers.sv
> +          // wrong data being used as basis for set/clear operations
It would be nice if you could give an example of exactly what would happen to this special bit. Ie show the _q value and _rdata for a TOR config which gives issues.

2023-03-24 13:15 UTC, silabs-oysteink approved these changes

2023-04-05 07:19 UTC, Silabs-ArjanB requested changes

2023-04-05 07:19 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +
This code has width mismatches. Why is only bit 0 treated specially and not also the other bits that have 'read legalization'?

2023-04-05 07:19 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +
Also, in general this PR affects pmp_addr_n_r, which as far as I know was correct, so its value should remain as it was.

2023-04-12 06:58 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +
The width should be correct. Only bit 0 is treated specially, because the other bits with read legalization are not implemented as flops, and are not represented in pmp_addr_n.
The change does fan into pmp_addr_n_r, but read legalization for this signal will still be set correctly.

2023-04-12 10:31 UTC, Silabs-ArjanB approved these changes

2023-04-12 10:31 UTC, merged