mret and wfi in User mode
openhwgroup/cv32e40s pull request #54
Opened 2021-09-21 09:23 UTC by silabs-oysteink

mret during user mode will result in illegal instruction.
WFI during user mode will result in illegal instruction if mstatus.tw == 1.

Added stalling of IF stage if WFI is present and CSR writes (including priv lvl updates via mret) is present in EX or WB.

2021-09-21 12:36 UTC, silabs-oivind commented on sva/cv32e40s_controller_fsm_sva.sv
Can you add a check for wfi resulting in illegal instruction as well?

2021-09-21 13:20 UTC, Silabs-ArjanB requested changes

2021-09-21 13:20 UTC, Silabs-ArjanB commented on sva/cv32e40s_controller_fsm_sva.sv
> +  // Check that a mstatus.tw is not written from WB while U-mode WFI is in ID
I find these assertions a bit counter-intuitive. There CAN be a WFI in ID while the tw is written, however in that case a stall must be caused. The reason this assertion works is because the stall suppresses the wfi_insn_id_i signal. I think a better assertion would be to use the decoder_ctrl_mux.wfi_insn signal and assert that there is a stall (ctrl_fsm_i.halt_id) when decoder_ctrl_mux.wfi_insn indicates that there is a WFI in ID and there is an instruction in EX or WB that can change tw and/or the privilege level.

Also we need similar assertions for mret.

2021-09-22 06:31 UTC, silabs-oysteink commented on sva/cv32e40s_controller_fsm_sva.sv
> +  // Check that a mstatus.tw is not written from WB while U-mode WFI is in ID
Updated assertions to check that mret and WFI are stalled in ID in case of CSR writes in EX or WB. The signals wfi_insn_id_i and mret_insn_id_i are not suppressed on stalls and should be safe to use. They are only suppressed in case of exceptions present in IF or ID, or a trigger match.

2021-09-22 07:18 UTC, Silabs-ArjanB approved these changes

2021-09-22 07:18 UTC, merged