Initial implementation of user mode changes and hazards.
openhwgroup/cv32e40s pull request #55
Opened 2021-09-24 11:55 UTC by silabs-oivind

Signed-off-by: Oivind Ekelund <oivind.ekelund@silabs.com>

2021-09-24 13:00 UTC, silabs-oysteink commented on rtl/cv32e40s_i_decoder.sv
> +                if (id_priv_lvl_i != PRIV_LVL_M) begin
Could update comment to be more precise

2021-09-24 13:00 UTC, Silabs-ArjanB requested changes
Mostly renaming. I don't see any functional issues, but I think we should aim at (eventually) moving the IF flop from the CSR file into the prefetcher to make all fetch related signals flow in the same manner.

2021-09-24 13:04 UTC, silabs-oysteink approved these changes

2021-09-24 13:04 UTC, Silabs-ArjanB reviewed
One more note: Should we maybe include most of the plumbing in the 40X as well counting on the fact that privilege level related flops will get optimized away as they will always indicate machine mode?

2021-09-27 10:52 UTC, silabs-oivind commented on rtl/cv32e40s_i_decoder.sv
> +                if (id_priv_lvl_i != PRIV_LVL_M) begin
I removed this comment, and also the comment about priv_lvl_i being safe to use in the WFI block. priv_lvl_i now comes directly from if_id_pipe, I don't see a need for a comment on why it's safe to use.

2021-09-27 10:52 UTC, silabs-oivind commented on rtl/cv32e40s_core.sv
> +  PrivLvl_t    priv_lvl_if, priv_lvl_lsu, current_priv_lvl;
Done

2021-09-27 10:52 UTC, silabs-oivind commented on rtl/cv32e40s_core.sv
> +    .priv_lvl_i            ( priv_lvl_lsu       ),
Done

2021-09-27 10:55 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +  always_ff @(posedge clk, negedge rst_n) begin
Agreed, but let's do it in a separate PR.

2021-09-27 10:55 UTC, silabs-oivind commented on rtl/cv32e40s_decoder.sv
> +       .id_priv_lvl_i (if_id_pipe_i.priv_lvl),
Done

2021-09-27 10:55 UTC, silabs-oivind commented on rtl/cv32e40s_decoder.sv
> +  input  if_id_pipe_t if_id_pipe_i,
Done

2021-09-27 10:55 UTC, silabs-oivind commented on rtl/cv32e40s_i_decoder.sv
> +   input  PrivLvl_t      id_priv_lvl_i, // Priviledge level for ID stage
Done

2021-09-27 10:56 UTC, silabs-oivind commented on rtl/cv32e40s_if_stage.sv
> +        if_id_pipe_o.priv_lvl         <= priv_lvl_i;
Agreed, but let's do this in a separate PR (in the PR moving priv-lvl logic to the prefetcher).

2021-09-27 11:02 UTC, silabs-oivind commented on rtl/cv32e40s_cs_registers.sv
> +    if (mstatus_we) begin
There is currently no CSR write - load/store hazard. But if added, this won't be needed.
A mstatus change due to change in flow control will not be an issue because of flushing.

2021-09-27 14:51 UTC, Silabs-ArjanB commented on rtl/cv32e40s_cs_registers.sv
> +    if (mstatus_we) begin
You are right; let's keep it as it is

2021-09-28 06:47 UTC, merged