Data independent timing
openhwgroup/cv32e40s pull request #76
Opened 2021-11-24 10:47 UTC by silabs-oivind

Commits b0464d47cbb7d90fd323196224b6591a9a790a14 and c51499941ecc82772d7c9479dbc37502e11d7491 are SEC clean.

2021-11-24 12:25 UTC, Silabs-ArjanB requested changes

2021-11-24 12:25 UTC, Silabs-ArjanB commented on docs/user_manual/source/xsecure.rst
> +* Stores to bufferable/non-bufferable address ranges.
Note that the addresses used by loads and stores will still provide a timing side-channel due to the following properties:

* Misaligned loads and stores differ in cycle count from aligned loads and stores.
* Stores to a bufferable address range react differently to wait states than stores to a non-bufferable address range.

Similarly the target address of branches and jumps will still provide a timing side-channel due to the following property:

* Branches and jumps to non-word-aligned non-RV32C instructions differ in cycle count from other branches and jumps.

These timing side-channels can largely be mitigated by imposing (branch target and data) alignment restrictions on the used software.

2021-11-24 12:25 UTC, Silabs-ArjanB commented on rtl/cv32e40s_ex_stage.sv
> +    if (xsecure_ctrl_i.cpuctrl.dataindtiming) begin
How is it guaranteed that the dataindtiming goes into effect on the instruction following a CSR write? (Same question for the usage of this bit in the DIV module). It seems to me that there is a hazard here.

Proposed fix: Make sure there can be no valid instruction in EX when there is a CSR write to cpuctrl in WB. (Something similar needs to be done for the random instruction insertion related to this CSR and the seed CSRs).

2021-11-25 12:42 UTC, silabs-oivind commented on docs/user_manual/source/control_status_registers.rst
> +| 4:2         | RW        | **dummyfreq**. Frequency control for dummy instruction insertion.      |
Updated.

2021-11-25 12:42 UTC, silabs-oivind commented on docs/user_manual/source/xsecure.rst
> +* Stores to bufferable/non-bufferable address ranges.
Updated.

2021-11-25 12:43 UTC, silabs-oivind commented on rtl/cv32e40s_ex_stage.sv
> +    if (xsecure_ctrl_i.cpuctrl.dataindtiming) begin
Now halting EX stage if there's a write to cpuctrl in WB.

2021-11-25 12:50 UTC, silabs-oysteink approved these changes

2021-11-26 07:36 UTC, Silabs-ArjanB requested changes

2021-11-26 07:36 UTC, Silabs-ArjanB commented on sva/cv32e40s_ex_stage_sva.sv
> +                     (wb_ready_i && $rose(id_ex_pipe_i.instr_meta.branch) && instr_valid && xsecure_ctrl_i.cpuctrl.dataindtiming)
I think that using $rose together with wb_ready_i makes it possible to miss checking some branches in this assertion. E.g. if wb_ready = 0 in the first EX cycle when $rose happens, then no check will be done

2021-12-09 10:20 UTC, silabs-oivind commented on rtl/cv32e40s_ex_stage.sv
> +    if (xsecure_ctrl_i.cpuctrl.dataindtiming) begin
Cpuctrl writes are now treated in a similar way as fencei.

2021-12-09 11:04 UTC, silabs-oysteink approved these changes

2021-12-09 12:21 UTC, Silabs-ArjanB approved these changes

2021-12-09 12:28 UTC, merged