Dummy Instruction Insertion
openhwgroup/cv32e40s pull request #82
Opened 2021-12-15 14:21 UTC by silabs-halfdan

Implemented Dummy Instruction Insertion and added related assertions.

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-12-15 15:55 UTC, Silabs-ArjanB commented on rtl/cv32e40s_if_stage.sv
> +  assign dummy_instr_if_o = dummy_insert;
Why is this output done?

2021-12-15 15:55 UTC, Silabs-ArjanB commented on rtl/cv32e40s_core.sv
> +    .dummy_instr_if_i           ( dummy_instr_if         ),
Why is this needed? Everything should pass through the if_id pipe registers.

2021-12-15 15:55 UTC, Silabs-ArjanB commented on rtl/cv32e40s_core.sv
> +    .dummy_instr_if_o    ( dummy_instr_if            ),
Why needed?

2021-12-15 15:55 UTC, Silabs-ArjanB commented on rtl/include/cv32e40s_pkg.sv
> +  parameter lfsr_cfg_t LFSR_CFG_DEFAULT = '{coeffs       : 32'h4536,
Why were these defaults changed? I thought we picked an invalid option on purpose initially?

2021-12-15 16:07 UTC, silabs-halfdan commented on rtl/cv32e40s_if_stage.sv
> +  assign dummy_instr_if_o = dummy_insert;
This is done to shift the lfsrs, but now that we have at least one cycle between dummy instructions it should be ok to use the if_id pipe register and shift one cycle later. I'll update the design.

2021-12-15 16:10 UTC, silabs-halfdan commented on rtl/include/cv32e40s_pkg.sv
> +  parameter lfsr_cfg_t LFSR_CFG_DEFAULT = '{coeffs       : 32'h4536,
Did not intend to PR this.
It was done to run the full test-suite with dummy instructions and valid lfsrs.

2021-12-16 09:31 UTC, Silabs-ArjanB commented on bhv/cv32e40s_rvfi.sv
> +        rvfi_order      <= is_dummy_instr_wb_i ? rvfi_order : rvfi_order + 64'b1;
I don't understand why you would need changes to line 672 and 689. Would changing 671 into the following instead also work?

if (wb_valid_i && !is_dummy_instr_wb_i) begin

It looks weird that rvfi_* signals are updated when rvfi_valid = 0

2021-12-16 09:37 UTC, silabs-halfdan commented on bhv/cv32e40s_rvfi.sv
> +        rvfi_order      <= is_dummy_instr_wb_i ? rvfi_order : rvfi_order + 64'b1;
That would work for 672, but the change on 689 would still be needed.

2021-12-16 10:10 UTC, silabs-oysteink approved these changes
No additional comments from me, approving given that the ongoing disuccion/changes will be done.

2021-12-16 10:50 UTC, silabs-halfdan commented on bhv/cv32e40s_rvfi.sv
> +        rvfi_order      <= is_dummy_instr_wb_i ? rvfi_order : rvfi_order + 64'b1;
I'll change it to only update output signals for valid rvfi retirements (i.e. wb_valid_i && !is_dummy_instr_wb_i).

2021-12-16 10:52 UTC, Silabs-ArjanB requested changes
Not all requirements have been implemented (missing 85.4.5)
RVFI related questions need to be answered first before I can review the rest of that file.

2021-12-16 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40s_dummy_instr.sv
> +  localparam CNT_WIDTH = $clog2(MAX_DUMMY_INTERVAL+1);
Explain the +1 (why is this counter different width than lfsr_cnt)?

2021-12-16 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40s_dummy_instr.sv
> +  assign lfsr_cnt   = xsecure_ctrl_i.lfsr0[29:24] & {xsecure_ctrl_i.cpuctrl.dummyfreq[5:2], 2'b11};
Can we drop the [5:2] here? (It is not according to spec and it is difficult to keep up to date with the package file type def)

2021-12-16 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40s_dummy_instr.sv
> +      cnt_q <= cnt_next;
Will this get clock gated when this feature is turned off?

2021-12-16 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40s_dummy_instr.sv
> +  assign cnt_next       = cnt_reset ? '0 : cnt_q + 1;
What is this counting (cycles or instructions)?

2021-12-16 10:52 UTC, Silabs-ArjanB commented on rtl/cv32e40s_if_stage.sv
> +//  assign dummy_instr_if_o = dummy_insert;
Remove comment

2021-12-16 10:52 UTC, Silabs-ArjanB commented on rtl/include/cv32e40s_pkg.sv
> +  logic [31:6] zero0;
Make this struct match the spec

2021-12-16 10:52 UTC, Silabs-ArjanB commented on sva/cv32e40s_id_stage_sva.sv
> +  a_no_trigger_match_on_dummy :
Can you add an additional assertion (not in this file) that there can be no synchronous exception on a dummy instruction?

2021-12-16 10:53 UTC, Silabs-ArjanB commented on rtl/cv32e40s_if_stage.sv
> +  assign dummy_instr_if_o = dummy_insert;
Okay, but actually I misread this. Based on the name I thought the entire instruction was being output here.

2021-12-16 11:16 UTC, silabs-halfdan commented on rtl/cv32e40s_cs_registers.sv
> +      assign lfsr_en = cpuctrl_q.dummyen && if_id_pipe_i.instr_meta.dummy;
Add separate enables and updating comment.

2021-12-16 11:24 UTC, silabs-halfdan commented on rtl/cv32e40s_dummy_instr.sv
> +  localparam CNT_WIDTH = $clog2(MAX_DUMMY_INTERVAL+1);
Adding comment

2021-12-16 11:32 UTC, silabs-halfdan commented on rtl/include/cv32e40s_pkg.sv
> +  logic [31:6] zero0;
Will update

2021-12-16 11:34 UTC, silabs-halfdan commented on rtl/cv32e40s_dummy_instr.sv
> +  assign lfsr_cnt   = xsecure_ctrl_i.lfsr0[29:24] & {xsecure_ctrl_i.cpuctrl.dummyfreq[5:2], 2'b11};
Yes, removing explicit indexing.

2021-12-16 11:47 UTC, silabs-halfdan commented on rtl/cv32e40s_dummy_instr.sv
> +      cnt_q <= cnt_next;
Only if the synth tools are smart enough, the data is gated with the feature enable. Can make the clock gating explicit.

2021-12-16 12:35 UTC, silabs-halfdan commented on rtl/cv32e40s_dummy_instr.sv
> +  assign cnt_next       = cnt_reset ? '0 : cnt_q + 1;
Currently counting cycles, will update to count instructions.

2021-12-16 13:12 UTC, silabs-halfdan commented on rtl/cv32e40s_if_stage.sv
> +//  assign dummy_instr_if_o = dummy_insert;
Done.

2021-12-16 13:18 UTC, Silabs-ArjanB requested changes
Can you also update the user manual?

Specifically section https://cv32e40s-user-manual.readthedocs.io/en/latest/xsecure.html#dummy-instruction-insertion should be self contained (no reference to Ibex manual). 

Also fix the ECC section, Security alert section and hardened CSR section as these we already implemented and there is no longer a need to refer to Ibex documentation.

2021-12-16 13:25 UTC, silabs-halfdan commented on sva/cv32e40s_id_stage_sva.sv
> +  a_no_trigger_match_on_dummy :
Will add one with the controller fsm assertions.

2021-12-16 15:20 UTC, silabs-halfdan commented on rtl/cv32e40s_controller_bypass.sv
> +      // Only dummy instructions can read non-zero data form R0
I agree, this is not correctly implemented. Was missing assertion to check that dummy instructions can read r0, adding that now and updating this code.

2021-12-16 15:23 UTC, Silabs-ArjanB commented on rtl/cv32e40s_controller_bypass.sv
> +      // Only dummy instructions can read non-zero data form R0
Now I see what you are doing here; correct, but not what I expected.

2021-12-16 15:25 UTC, silabs-halfdan commented on rtl/cv32e40s_controller_bypass.sv
> +      // Only dummy instructions can read non-zero data form R0
But still missing the special case for R0 reads for dummy instructions

2021-12-16 15:48 UTC, Silabs-ArjanB commented on rtl/cv32e40s_controller_bypass.sv
> +        ctrl_byp_o.operand_a_fw_mux_sel = SEL_ZERO;
The SEL_ZERO logic should be done in the register file instead

2021-12-16 15:49 UTC, Silabs-ArjanB commented on rtl/cv32e40s_controller_bypass.sv
> +    if (if_id_pipe_i.instr_meta.dummy) begin
SEL_LFSR should be prevented when reading R0

2021-12-16 15:52 UTC, Silabs-ArjanB requested changes

2021-12-16 16:30 UTC, silabs-halfdan commented on rtl/cv32e40s_register_file.sv
> +    // loop over all regitstrers, R0 can be used by dummy instructions
Now implemented as on ibex

2021-12-16 16:30 UTC, silabs-halfdan commented on rtl/cv32e40s_controller_bypass.sv
> +        ctrl_byp_o.operand_a_fw_mux_sel = SEL_ZERO;
Moved to the register file

2021-12-16 16:31 UTC, silabs-halfdan commented on rtl/cv32e40s_controller_bypass.sv
> +    if (if_id_pipe_i.instr_meta.dummy) begin
Added special case for addr==0

2021-12-16 16:31 UTC, silabs-halfdan commented on rtl/cv32e40s_dummy_instr.sv
> +  assign dummy_insert_o = (cnt_q > lfsr_cnt) && ctrl_fsm_i.allow_dummy_instr && xsecure_ctrl_i.cpuctrl.rnddummy;
Will add

2021-12-17 10:21 UTC, silabs-oysteink requested changes

2021-12-17 10:21 UTC, silabs-oysteink commented on rtl/cv32e40s_controller_bypass.sv
> +      if (rf_raddr_i[0] != 32'h0) begin
rf_raddr_i is not 32 bit wide.

2021-12-17 10:21 UTC, silabs-oysteink commented on rtl/cv32e40s_controller_bypass.sv
> +      if (rf_raddr_i[1] != 32'h0) begin
Same as above

2021-12-17 10:21 UTC, silabs-oysteink commented on rtl/cv32e40s_wb_stage.sv
> +  logic                 block_r0_we;
Signal unused, should be removed

2021-12-17 10:21 UTC, silabs-oysteink commented on sva/cv32e40s_id_stage_sva.sv
> +      else `uvm_error("id_stage", "Dummy instruction could not read from R0 (on read port 1)")
Error message should say read port 0

2021-12-17 11:59 UTC, silabs-halfdan commented on rtl/cv32e40s_controller_bypass.sv
> +      if (rf_raddr_i[0] != 32'h0) begin
Fixed

2021-12-17 11:59 UTC, silabs-halfdan commented on rtl/cv32e40s_controller_bypass.sv
> +      if (rf_raddr_i[1] != 32'h0) begin
Fixed

2021-12-17 12:00 UTC, silabs-halfdan commented on rtl/cv32e40s_wb_stage.sv
> +  logic                 block_r0_we;
Removed

2021-12-17 12:01 UTC, silabs-halfdan commented on sva/cv32e40s_id_stage_sva.sv
> +      else `uvm_error("id_stage", "Dummy instruction could not read from R0 (on read port 1)")
Fixed

2021-12-17 12:09 UTC, silabs-oysteink approved these changes

2021-12-17 12:14 UTC, merged